Silverstripe 4 namespace fixes
stevie-mayhew/silverstripe-svg pull request #11
Opened 2017-06-29 02:11 UTC by adrexia

The only major change to get this module to work was namespaces. I've tested all the scenarios I could think off, and they all worked perfectly. Getting the CMS upload stuff to work was tricky, but that's much less about this module and more about the FileSystem changes. :)

2017-08-22 21:11 UTC, adrexia commented
Hey @stevie-mayhew, have you had a chance to test this at all? Any changes I need to make?

2017-08-22 23:39 UTC, stevie-mayhew requested changes

2017-08-22 23:39 UTC, stevie-mayhew commented on composer.json
> +        "silverstripe/framework": "~4.0.0-alpha7"
@adrexia Can we make this `~4.0` so we dont have to change it later?

2017-08-22 23:39 UTC, stevie-mayhew commented on composer.json
> +        "silverstripe/framework": "~4.0.0-beta1"
Can we make this ^4.0 and I can merge :)

2017-08-22 23:58 UTC, adrexia commented
Done!

2017-08-23 05:12 UTC, stevie-mayhew approved these changes

2017-08-23 05:12 UTC, merged

2017-08-23 05:13 UTC, adrexia commented
Thanks!